@echo off
echo Testing login endpoint...
powershell -Command "$body = '{\"email\":\"vikash.tripathi@example.com\",\"password\":\"StrongPass123\"}'; try { $response = Invoke-WebRequest -Uri 'http://localhost:8081/api/auth/login' -Method POST -Body $body -ContentType 'application/json' -UseBasicParsing; Write-Host 'Status:' $response.StatusCode; Write-Host 'Response:' $response.Content } catch { Write-Host 'Error:' $_.Exception.Message }"
